version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.10.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby
    versions:
    - 2.28.0
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.6.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-image
    versions:
    - 2.7.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.6.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.8.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.7.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 2.7.0
    - 4.0.1
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.6.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.8.0
  - dependency-name: object-path
    versions:
    - 0.11.5
